config/routes.rb
Hnclone::Application.routes.draw do

  root :to => "submissions#index"

  resource :session, :only => [:create, :destroy, :new]

  resources :users, :except => [:index]

  resources :submissions do
    resources :comments do #REV: so first one for the direct replies, then another
      resources :comments #REV: for all children?
    end
    post "upvote"
    post "remove_upvote"
  end

  resources :comments, :only => [:new, :create]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id            :integer          not null, primary key
#  body          :text
#  author_id     :integer
#  parent_id     :integer
#  submission_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Comment < ActiveRecord::Base
  attr_accessible :body, :author_id, :parent_id, :submission_id

  belongs_to :author, :class_name => "User", :foreign_key => :author_id
  belongs_to :parent, :class_name => "Comment", :foreign_key => :parent_id
  belongs_to :submission
end

app/models/comment_ancestor.rb
class CommentAncestor < ActiveRecord::Base
  attr_accessible :ancestor_id, :descendant_id
end

app/models/email.rb
# == Schema Information
#
# Table name: emails
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Email < ActiveRecord::Base
  attr_accessible :user_id, :email

  belongs_to :user

  validates :email, :presence => true, :uniqueness => true
end

app/models/submission.rb
# == Schema Information
#
# Table name: submissions
#
#  id          :integer          not null, primary key
#  url         :string(255)
#  title       :string(255)
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Submission < ActiveRecord::Base
  attr_accessible :url, :title, :description, :user_id, :comments_attributes

  has_many :comments
  accepts_nested_attributes_for :comments, :reject_if => :all_blank

  has_many :thread_upvotes
  belongs_to :user

  def total_upvotes
    ThreadUpvote.where("submission_id = ?", self.id).count
  end

  def upvote(user_id)
    ThreadUpvote.create!(:submission_id => self.id, :user_id => user_id)
    User.find(user_id).add_karma
  end

  def remove_upvote(user_id)
    ThreadUpvote.where(:submission_id => self.id, :user_id => user_id)[0].destroy
    User.find(user_id).remove_karma
  end

  def user_voted?(user_id)
    ThreadUpvote.where(:submission_id => self.id, :user_id => user_id).exists?
  end
end

app/models/thread_upvote.rb
# == Schema Information
#
# Table name: thread_upvotes
#
#  id            :integer          not null, primary key
#  submission_id :integer
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class ThreadUpvote < ActiveRecord::Base
  attr_accessible :submission_id, :user_id

  belongs_to :submission
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  username   :string(255)
#  password   :string(255)
#  karma      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :username, :password, :karma, :emails_attributes

  has_many :submissions
  has_many :comments
  has_many :thread_upvotes

  has_many :emails
  accepts_nested_attributes_for :emails, :reject_if => :all_blank

  validates :username, :presence => true, :uniqueness => true

  def add_karma
    self.karma += 1
    self.save
  end

  def remove_karma
    self.karma -= 1
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment])

    if @comment.save
      comment = @comment.dup

    until comment.parent_id.nil?
      ca = CommentAncestor.create!(
        :ancestor_id => comment.parent_id,
        :descendant_id => @comment.id
      )
      comment = Comment.find(ca.ancestor_id)
    end


      flash[:success] = "Comment posted"
      redirect_to @comment.submission
    else
      flash[:error] = "There was an error posting your comment"
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
     if log_in(params[:user][:username], params[:user][:password])
       redirect_to submissions_url
     else
       render :new
     end
   end

  def destroy
   log_out
   redirect_to new_user_url
  end

  def new
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def index
    @submissions = Submission.all
  end

  def new
    @submission = Submission.new
    @submission.comments.build
  end

  def create
    @submission = Submission.new(params[:submission])

    if @submission.save
      flash[:success] = "Submission added"
      @submission.user.add_karma
      redirect_to @submission
    else
      flash[:error] = "There was an error adding your submission"
      render :new
    end
  end

  def show
    @submission = Submission.find(params[:id])
  end

  def upvote
    submission = Submission.find(params[:submission_id])
    if logged_in? && !submission.user_voted?(current_user.id)
      submission.upvote(current_user.id)
      flash[:success] = "Upvote added"
    else
      flash[:error] = "You have either already voted or are not logged in"
    end
    redirect_to submission
  end

  def remove_upvote
    submission = Submission.find(params[:submission_id])
    if logged_in? && submission.user_voted?(current_user.id)
      submission.remove_upvote(current_user.id)
      flash[:success] = "Upvote removed"
    else
      flash[:error] = "You havent already voted or are not logged in"
    end
    redirect_to submission
  end

  def edit
    @submission = Submission.find(params[:id])
  end

  def update
    @submission = Submission.find(params[:id])
    @submission.update_attributes(params[:submission])

    if @submission.save
      flash[:success] = "Submission updated"
      redirect_to @submission
    else
      flash[:error] = "There was an error updating your submission"
      render :edit
    end
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    3.times { @user.emails.build }
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:success] = "Account successfully created"
      redirect_to new_session_path
    else
      flash[:error] = "There were some errors creating your account"
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Account successfully deleted"
    redirect_to submissions_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  #NOTE TO SELF. THIS IS AN N+1 QUERY. FIND A WAY TO NOT N+! THIS.!!!!!!!!
  def make_tree(submission_id) #REV: Glad to see you're pushing yourself
    tree = []

    comments = Submission.find(submission_id).comment_ids

    comments.each do |comment_id|
      branch = CommentAncestor.where(:ancestor_id => comment_id)
      tree << branch #REV: this would return only one layer, right?
    end
    tree
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(username, password)
    user = User.find_by_username(username)
    if password == user.password
      user.remember_token = SecureRandom.hex(16)
      user.save!

      session[:remember_token] = user.remember_token

      true
    else
      false
    end
  end

  def current_user
    return nil if session[:remember_token].nil?
    @user ||= User.find_by_remember_token(session[:remember_token])
  end

  def log_out
    current_user.remember_token = nil
    current_user.save!

    session[:remember_token] = nil
  end

  def logged_in?
    not current_user.nil?
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1> Post a reply to </h1>

<%= form_tag("/comments", :method=> :post) do %>
  <textarea name="comment[body]"></textarea>
  <input type="hidden" name=comment[author_id]
    value="<%= current_user.id %>">
  <input type="hidden" name=comment[parent_id]
      value="<%= params[:comment_id] %>">
  <input type="hidden" name=comment[submission_id]
    value="<%= params[:submission_id] %>">
  <br>
  <input type="submit" value ="Post Comment" class="btn btn-primary">
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse">
<div class="navbar-inner">
  <div class="container">
      <ul class="nav">
        <li>
          <a class ="brand" href="/">
               &nbsp; &nbsp; &nbsp; Hacker News
          </a>
        </li>
      </ul> <!-- NAV -->
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hnclone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "layouts/header" %>
  <div class="container">
    <div class="well">
        <%= yield %>
      </div>
    </div>
    <%= current_user %>
</body>
</html>

app/views/submissions/index.html.erb
<h1>All Submissions</h1>

<table class="table table-striped">
  <tr>
    <td>Submssion Title</td>
    <td>Author</td>
    <td>Points</td>
    <td>Submission Time</td>
    <td>Comments</td>
  </tr>
    <% @submissions.reverse_each do |sub| %>
      <tr align="center">
        <td><%= link_to sub.title, sub.url %></td>
        <td><%= link_to sub.user.username, sub.user %></td>
        <td><%= sub.total_upvotes %></td>
        <td><%= "#{time_ago_in_words(sub.created_at)} ago" %></td>
        <td><%= link_to sub.comments.count, sub %></td>
      </tr>
    <% end %>
</table>

<br>
<%= link_to "Add new submission", new_submission_path, class: "btn" %>

app/views/submissions/new.html.erb
<h1>Add a submission</h1>
<%= form_for @submission do |f| %>
  <%= f.label(:title) %>
  <%= f.text_field(:title) %>
  <br>
  <%= f.label(:url) %>
  <%= f.text_field :url, :value => "http://" %>
  <br>
    <%= f.fields_for(:comments) do |comment_form| %>
      <%= comment_form.label(:body, "Comment") %>
      <%= comment_form.text_area :body, :size => "30x5" %>
      <%= comment_form.hidden_field :author_id, :value => current_user.id %>
    <% end %>
  <br>
  <input type="hidden" name="submission[user_id]"
    value="<%= current_user.id %>" />
  <%= f.submit class: "btn btn-large" %>
<% end %>

app/views/submissions/show.html.erb
<!-- REV: got a error here when I ran it... calling id on nil -->

<h1>Submission #<%= @submission.id %></h1>

<h2><%= link_to @submission.title, @submission.url %></h2>
Submitted by: <%= link_to @submission.user.username, @submission.user %>, <%= "#{time_ago_in_words(@submission.created_at)} ago" %>
<br>
<br>
Points: <%= @submission.total_upvotes %>
<br>
<br>
<% if !@submission.user_voted?(current_user) %>
  <%= button_to "Upvote", submission_upvote_url(@submission), class: "btn" %>
<% else %>
  <%= button_to "Remove Upvote", submission_remove_upvote_url(@submission),
      class: "btn btn-danger" %>
<% end %>

<h3>Comments: ( <%= @submission.comments.count %> )</h3>
<br>

<%= form_tag("/comments", :method=> :post) do %>
  <textarea name="comment[body]"></textarea>
  <input type="hidden" name=comment[author_id]
    value="<%= current_user.id %>">
  <input type="hidden" name=comment[submission_id]
    value="<%= @submission.id %>">
  <br>
  <input type="submit" value ="Post Comment" class="btn btn-primary">
<% end %>
<br>
<br>
<% @submission.comments.each do |comment| %>
  <div class="well well-small">
    <%= comment.body %>
    <br>
    <em>Posted by <%= link_to comment.author.username, comment.author %> <%=  "#{time_ago_in_words(@submission.created_at)} ago" %></em> -
    <%= link_to "Reply", new_submission_comment_comment_url(@submission, comment) %>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>Create a user</h1>

<%= form_for @user do |f| %>
  <%= f.label(:username) %>
  <%= f.text_field(:username) %>
  <br>
  <%= f.label(:password) %>
  <%= f.password_field(:password) %>
  <br>
  <br>
  You may add up to 3 emails.
  <br>
  <%= f.fields_for(:emails) do |email_form| %>
  <br>
    <%= email_form.label(:email, "Email")%>
    <%= email_form.text_field(:email) %>
  <% end %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>

<b>SignUp Date:</b> <%= @user.created_at.to_date %>
<br>
<br>
<ul>
  <% @user.emails.each do |email| %>
  <li> <%= email.email %> </li>
  <% end %>
</ul>
<br>

<table class="table table-striped">
  <tr>
    <td>Submssion Title</td>
    <td>Points</td>
    <td>Submission Time</td>
    <td>Comments</td>
  </tr>
    <% @user.submissions.reverse_each do |sub| %>
      <tr align="center">
        <td><%= link_to sub.title, sub.url %></td>
        <td><%= sub.total_upvotes %></td>
        <td><%= "#{time_ago_in_words(sub.created_at)} ago" %></td>
        <td><%= link_to sub.comments.count, sub %></td>
      </tr>
    <% end %>
</table>